{"name": "Проверка невозможности создания курьера с существующим логином (двух одинаковых курьеров)", "status": "passed", "description": "Проверяем, что при попытке создать курьера с существующим логином, возвращается ошибка с кодом ответа - 409 и текстом \"Этот логин уже используется. Попробуйте другой.\"", "steps": [{"name": "Генерация login, password и first_name курьера", "status": "passed", "start": 1705859708019, "stop": 1705859708019}, {"name": "Создаем курьера", "status": "passed", "parameters": [{"name": "data", "value": "{'login': 'wfnpubsxtb', 'password': 'bauliujuhu', 'firstName': 'tbfsawjbie'}"}], "start": 1705859708019, "stop": 1705859708102}, {"name": "Создаем курьера", "status": "passed", "parameters": [{"name": "data", "value": "{'login': 'wfnpubsxtb', 'password': 'bauliujuhu', 'firstName': 'tbfsawjbie'}"}], "start": 1705859708102, "stop": 1705859708202}], "attachments": [{"name": "stdout", "source": "46919ae1-4360-4514-8d42-309e76c326b5-attachment.txt", "type": "text/plain"}], "start": 1705859708018, "stop": 1705859708202, "uuid": "2282e9ec-8c34-4ccd-a41c-1db0ebba1af6", "historyId": "cc0e9f0d8bb9e024a34e10c0ac100de4", "testCaseId": "cc0e9f0d8bb9e024a34e10c0ac100de4", "fullName": "tests.test_create_courier#test_create_courier_existed_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "36652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}