{"name": "Параметризированная проверка невозможности авторизации курьера, если неправильно указано одно из обязательных полей (login/password)", "status": "passed", "description": "Проверяем, что при попытке авторизации курьера с некорректно указанным одним из обязательных полей возвращается ошибка с кодом ответа 404, и текстом \"Учетная запись не найдена\"", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login_pass", "value": "['maria98765', 'Qwerty123']"}], "start": 1705859709480, "stop": 1705859709545}], "parameters": [{"name": "data", "value": "['maria98765', 'Qwerty123']"}], "start": 1705859709479, "stop": 1705859709545, "uuid": "55e71650-b9d6-4972-8bad-f34a12ed09fc", "historyId": "c5e32e39246dc8665a6c6f7de35874c2", "testCaseId": "378201d3eaaa7b564c47a8636770ad5e", "fullName": "tests.test_login_courier#test_negative_login_with_incorrect_required_field", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "host", "value": "HOME-PC"}, {"name": "thread", "value": "36652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}